services:
  main-server:
    image: main-server:latest
    container_name: main-server
    ports:
      - "8080:8080"
    environment:
      DB_URL_SERVER: ${DB_URL_SERVER}
      DB_USERNAME_SERVER: ${DB_USERNAME_SERVER}
      DB_PASSWORD_SERVER: ${DB_PASSWORD_SERVER}
    depends_on:
      - mysql
    restart: always